# Generated by Django 4.2.29 on 2026-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('course', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('Computer', 'Computer Science'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Commerce', 'Commerce'), ('Other', 'Other')], max_length=50)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-enrolled_on'],
            },
        ),
    ]
